# Multiple Linear Regression in Python using SciKitLearn

In this program we want to predict startups profits using a linear regression model.

**Dataset Description**

The dataset is composed by 50 rows that correspond the total of startup and 5 columns. The features of the problem are: R&D Spend, Administration, Marketing Spend and City. The response is the Profit column. Based on these feature we are going to construct the model.

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd

## Importing the Dataset

In [2]:
dataset = pd.read_csv('50_Startups.csv') # Reading the dataset and creating the dataframe
X = dataset.iloc[:, :-1].values # Creating feature array
y = dataset.iloc[:, -1].values # Creating the response array

## Data Preprocessing

In this problem the column City must be modified into numerical values.

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X[0:5])

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


## Splitting the Dataset into Training and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)